### ISSUE TITLE
Missing training data

### ISSUE THREAD

**Issue by zsc** [PeiqinSun/tf-tutorials#1]
@yuekai146 
如果训练数据不大，可以直接push到这个repo里。

**Comment by PeiqinSun** [comment]
已经把数据集的超链接贴到Homework1当中. 请注意要下降format2, 即.mat格式。

**Comment by PeiqinSun** [comment]
使用student进行训练的同学是可以直接获取到数据集的, 所以也可以直接从阿里云直接下载数据集。
