### ISSUE TITLE
如何提交作业

### ISSUE THREAD

**Issue by Lavande233** [PeiqinSun/tf-tutorials#11]
请问作业在本地运行的应该如何提交？

**Comment by PeiqinSun** [comment]
我们会在下节课公布作业提交的方式, 目前定为是打成tar包通过网页进行上传。

**Comment by yeoyi519** [comment]
> 我们会在下节课公布作业提交的方式, 目前定为是打成tar包通过网页进行上传。

不是下节课前交作业最多能拿100分吗，到时候才宣布的话，最多不就只有90分了？
