### ISSUE TITLE
阿里云体验的相关问题

### ISSUE THREAD

**Issue by sixingdeguo** [PeiqinSun/tf-tutorials#13]
-求助：我在使用服务器时，会出如下的错误，NUM0-7情况都一样，不知道如何解决。
![_20190306104046](https://user-images.githubusercontent.com/44903525/53863202-896af800-4024-11e9-8484-1be021954ca9.png)

**Comment by chynphh** [comment]
尝试命令
CUDA_VISIBLE_DEVICES=4 python train.py
不用加$和{}
