### ISSUE TITLE
Which combination of  versions of tf, cuda and cudnn is recommended?(gpu)

### ISSUE THREAD

**Issue by YuanJ-i** [PeiqinSun/tf-tutorials#15]

**Comment by tiny-fisher** [comment]
tf-CPU needs cuda and cudnn?

**Comment by PeiqinSun** [comment]
我们的tutorials都是基于tensorflow1.12.0编写。而cuda和cudnn只要能和自己机器的显卡驱动搭配即可。cpu版本的tf不需要gpu的支持

**Comment by PeiqinSun** [comment]
我们的tutorials都是基于tensorflow1.12.0编写。而cuda和cudnn只要能和自己机器的显卡驱动搭配即可。cpu版本的tf不需要gpu的支持，所以不需要cuda和cudadnn

**Comment by YuanJ-i** [comment]
> 
> 
> 我们的tutorials都是基于tensorflow1.12.0编写。而cuda和cudnn只要能和自己机器的显卡驱动搭配即可。cpu版本的tf不需要gpu的支持，所以不需要cuda和cudadnn

谢谢回复 明白了
