### ISSUE TITLE
能否直接提供docker下载

### ISSUE THREAD

**Issue by zsc** [PeiqinSun/tf-tutorials#16]
有同学想在自已机器上用。

**Comment by PeiqinSun** [comment]
可以的。但我目前用的镜像是支持cuda9.0

**Comment by zsc** [comment]
那给个不需要GPU的docker?

**Comment by PeiqinSun** [comment]
我需要看一下有没有相应的基础镜像. 若没有, 就得自己配一个。时间?

**Comment by wxmkevin** [comment]
上节课最后老师说是会帮我们配一个docker的。

**Comment by zsc** [comment]
周三前出吧

**Comment by PeiqinSun** [comment]
已经给出cpu的docker. 但不建议给gpu docker. 因为gpu docker要求同学们需要自己安装对应的nvidia driver。这样无法给出统一的脚本。
