### ISSUE TITLE
作业提交命名

### ISSUE THREAD

**Issue by jackeyli81** [PeiqinSun/tf-tutorials#21]
我看过了1a.md，意思是不是在服务器运行时，尽量命令行输入没有定位参数(argparse)？例子：
python train.py                                    (good)
python train.py --loss softmax            (bad)
我理解是，作业要求每次修改的参数需要在脚本里体现。

**Comment by perrylover** [comment]
我们以改动代码最少为判定标准，如果将参数在脚本中体现，相应的改动会变多(diff文件会变大)。
