### ISSUE TITLE
Training data size for homework 1a

### ISSUE THREAD

**Issue by chu-tianxiang** [PeiqinSun/tf-tutorials#22]
In Homework 1a Q2, by "reduce the amount of images labelled with'8' '9' and '0' to 500 and get Dataset A" do you mean 500 for each label or for the sum of all three labels?

**Comment by PeiqinSun** [comment]
I think it should be each label. @perrylover

**Comment by perrylover** [comment]
Yes. It is for each label, which means the sum of all three labels are 1500.
