### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by stdDeepDark** [PeiqinSun/tf-tutorials#24]
安装tensorflow-gpu等组件后，涉及tf的很多代码运行开始报错，是什么配置信息有误吗
![image](https://user-images.githubusercontent.com/39540972/54284008-2a842080-45da-11e9-9fbf-e8b014d3878c.png)

**Comment by PeiqinSun** [comment]
先确认自己的tensorflow版本是否正确 以及 能否正常运行相应的简单程序。

**Comment by stdDeepDark** [comment]
更换tensorflow-gpu版本后正常了，但是在运行02-svhn最后一块时出了这个问题
![image](https://user-images.githubusercontent.com/39540972/54353950-519d2980-4690-11e9-967c-86aa28d4d66c.png)

**Comment by stdDeepDark** [comment]
上面那条应该是变量命名不一致，“epoch”是“for e in range(nr_epoch):”的“e”
