### ISSUE TITLE
diff 比较对象

### ISSUE THREAD

**Issue by QAQ-v** [PeiqinSun/tf-tutorials#26]
比较的对象是整个文件夹还是只是改动的文件，eg:
diff -u 01-svhn/ 01-svhn.xx/ 还是
diff -u 01-svhn/dataset.py 01-svhn.xx/dataset.py

因为如果以文件夹为比较对象的话，每次diff文件里会输出以下类似冗余信息导致diff文件size增大
Common subdirectories: 01-svhn/__pycache__ and 01-svhn.fulldata/__pycache__
Common subdirectories: 01-svhn/images and 01-svhn.fulldata/images
Common subdirectories: 01-svhn/train_log and 01-svhn.fulldata/train_log

**Comment by zsc** [comment]
Common subdirectories 这些行不算。
