### ISSUE TITLE
作业1 Q3 diff文件命名

### ISSUE THREAD

**Issue by yeoyi519** [PeiqinSun/tf-tutorials#29]
作业1
Q2中全训练集的diff文件没有all后缀，说明中写的是q2.a.diff q2.b.diff q2.c.diff；非全训练集都要加size；
Q4中全训练集的diff文件有all后缀，说明中写的是q4.all.diff；非全训练集都要加size；
那么，
Q3中全训练集的diff文件是 q3.a.all.diff 还是 q3.a.diff？
Q3 Optional 应该是可选的作业吧？说明中写的是 q3.o1.diff，意思是只用在全训练集上做实验？

**Comment by yeoyi519** [comment]
另外，可选作业的加分标准是什么？

**Comment by perrylover** [comment]
Q3命名规则，反色增广， 全数据集q3.a.all.diff, 30000数据q3.a.30000.diff；仿射变换，全数据集q3.b.all.diff, 30000数据q3.b.30000.diff
optional加分标准确定后再给出，可只在全数据集上作实验
