### ISSUE TITLE
没懂Mixup(a data-agnostic augmentation technique)是什么增广方式

### ISSUE THREAD

**Issue by wxx07** [PeiqinSun/tf-tutorials#30]
如题
原本以为是增广方式的混合，结果q3 optional已经有了

**Comment by PeiqinSun** [comment]
这是单独的一种增广方式。以二分类为例, 其目标是为了让模型学会线性地区分正例与负例之间的"中间例", 即能显式地让模型学会如何判别一个不确定的目标的分数。详情可以看具体的paper. 
《mixup：BEYOND EMPIRICAL RISK MINIMIZATION》
