### ISSUE TITLE
deadline前后各提交一次作业的评分标准？

### ISSUE THREAD

**Issue by yeoyi519** [PeiqinSun/tf-tutorials#31]
如果在deadline前提交一次作业，经过实验课讲评后发现之前的错了或者不好，然后重新修改了一份作业提交，这时的评分标准是怎样的？两次分别计算取最高，还是直接就不允许第二次提交？

**Comment by PeiqinSun** [comment]
原则上取两者最高。但要切记,  第二次上交作业只有90分最高。
