### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by nht2018** [PeiqinSun/tf-tutorials#32]
求助
我在运行train.py时报错
  File "D:/Personal/Desktop/tf-tutorials/01-svhn/train.py", line 22, in get_dataset_batch
    ds = tf.data.Dataset().from_generator(ds_gnr, output_types=(tf.float32, tf.int32))

TypeError: Can't instantiate abstract class DatasetV1 with abstract methods _as_variant_tensor, _inputs
tensorflow版本是1.13.1

**Comment by chu-tianxiang** [comment]
试试改成ds = tf.data.Dataset.from_generator(ds_gnr, output_types=(tf.float32, tf.int32))

**Comment by nht2018** [comment]
解决了
感谢 chu-tianxiang
