### ISSUE TITLE
提交作业的网站拒绝访问

### ISSUE THREAD

**Issue by yeoyi519** [PeiqinSun/tf-tutorials#33]

**Comment by yeoyi519** [comment]
![捕获](https://user-images.githubusercontent.com/37505431/54530445-bf619200-49bd-11e9-8048-2894d8124e68.PNG)

**Comment by PeiqinSun** [comment]
之前处于更新状态。现已开放！！

**Comment by yeoyi519** [comment]
> 之前处于更新状态。现已开放！！

提交到一半又挂了，也不知道交上去没交上去，能不能换一个方式交作业，比如邮箱？

**Comment by yeoyi519** [comment]
ok，可以正常访问了
