### ISSUE TITLE
服务器账号

### ISSUE THREAD

**Issue by fwzzz** [PeiqinSun/tf-tutorials#34]
“We will assign an IP address and a port number to everyone, then you can log in via ssh. e.g. ssh root@40.104.61.196 -p 8100”
请问什么时候给每个人提供GPU的服务器账号？

**Comment by zsc** [comment]
因为一些客观困难，我们无法全员提供GPU。实验都已改成CPU可做的规模。
https://github.com/PeiqinSun/tf-tutorials/blob/master/Course%20announcement.md#gpu-servers
