### ISSUE TITLE
作业多次上交失败 ， 文件名也是按格式的 ，tar包里面也就是报告跟一系列diff文件 ，试了好几次了 ，每次都报错。能不能换种交作业的方法，服务器里面打包都尝试了好几次了，就是upload报错。

### ISSUE THREAD

**Issue by xuebaliang** [PeiqinSun/tf-tutorials#37]

**Comment by xuebaliang** [comment]
懵逼了呀，上传截图失败，反正文件格式没有文件，每个文件都显示了大小。

**Comment by xuebaliang** [comment]
懵逼了呀，文件格式没有问题，里面的文件大小也都显示了。

**Comment by chynphh** [comment]
提示什么错误？

**Comment by xuebaliang** [comment]
There are some unwanted files in tarfile or the name of file is wrong

**Comment by xuebaliang** [comment]
我的tar包里面是一个pdf文件，外加十几个类似于q1.a.10000.diff的diff文件

**Comment by chynphh** [comment]
能贴出你diff的文件列表吗？

**Comment by xuebaliang** [comment]
我开始本来要上传图片的  但是github是不是上传不了

**Comment by chynphh** [comment]
贴文字就行。
或者你可以先上传文件子集，比如打包提交你q2.a.diff。 会提示你缺少哪些文件。
重复上传会替换同名文件

**Comment by xuebaliang** [comment]
![6HN_4LZ9C~G5XJEP ZE_3A3](https://user-images.githubusercontent.com/35771028/54590578-651b0c80-4a63-11e9-9fb0-4ddfadc5a799.png)

**Comment by xuebaliang** [comment]
这样子

**Comment by xuebaliang** [comment]
怎么破   我一个一个打包传？

**Comment by chynphh** [comment]
不用啊，你提交一个就知道你多了哪些，少了哪些。
图片里q3.a.diff应该是q3.a.all.diff

**Comment by xuebaliang** [comment]
对名字还有设置的啊  好吧  我再试一遍 谢谢

**Comment by xuebaliang** [comment]
那第一问 第二问的用全部数据集的需要加all么

**Comment by chynphh** [comment]
不需要
每个问题都有很详细的命名规则，见Homework_1a.md。

**Comment by xuebaliang** [comment]
好的  谢谢

**Comment by PeiqinSun** [comment]
问题在于你的q3.a.diff命名是错误的。应该命名为q3.a.all.diff

**Comment by xuebaliang** [comment]
好的好的 刚刚重新打包提交了一次  成功了 谢谢老师
