### ISSUE TITLE
import custom_vgg16_bn as vgg16

### ISSUE THREAD

**Issue by xuebaliang** [PeiqinSun/tf-tutorials#40]
weights_path = os.path.abspath(dir_path + "/../models/vgg16_onnx.npy")
老师，请问一下，没有找到custom_vgg16_bn这个包或者类的下载地址呀，链接里面只有vgg16_onnx.npy文件

**Comment by perrylover** [comment]
custom_vgg16_bn.py 里面有一个model类，vgg16_onnx.npy是model类里面不同层对应的权重
