### ISSUE TITLE
第二次作业train_log过大

### ISSUE THREAD

**Issue by boxcannon** [PeiqinSun/tf-tutorials#44]
第二次作业的train_log过大，程序刚刚开始运行，就超出服务器的容量限制

**Comment by perrylover** [comment]
试试把config.show_interval调大一些？

**Comment by boxcannon** [comment]
> 试试把config.show_interval调大一些？
我把config.snapshot_interval调大之后好像解决这个问题了

**Comment by boxcannon** [comment]
> 试试把config.show_interval调大一些

我试着调大了config.snapshot_interval好像解决了这个问题，谢谢
