### ISSUE TITLE
作业提交出错

### ISSUE THREAD

**Issue by QAQ-v** [PeiqinSun/tf-tutorials#45]
作业1提交
因为没看到有作业1的截止日期就稍晚了几天。
upload之后就显示无法访问此页面。链接已重置
页面显示信息如下：

无法访问此网站 连接已重置。
请试试以下办法：

- 检查网络连接
- 检查代理服务器和防火墙
- 运行 Windows 网络诊断

ERR_CONNECTION_RESET

**Comment by zsc** [comment]
试下群里说的用手机4G网提交

**Comment by PeiqinSun** [comment]
下次这种问题反馈给助教: 程昊同学。
