### ISSUE TITLE
无法登陆提交作业的网站

### ISSUE THREAD

**Issue by fwzzz** [PeiqinSun/tf-tutorials#49]
作业1完成得晚了一些，完成后想提交，但网站一直崩溃，提示：

无法访问此网站 连接已重置。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_RESET

**Comment by zsc** [comment]
试下群里说的用手机4G网提交

**Comment by PeiqinSun** [comment]
已重置。下次这种现象直接给助教反馈即可。
