### ISSUE TITLE
student account login the server, but No space left on device

### ISSUE THREAD

**Issue by changcui** [PeiqinSun/tf-tutorials#5]
mkdir under ~/students error
mkdir: cannot create directory 'changcui': No space left on device

**Comment by zsc** [comment]
已清理，但是存储还是太少，我们再研究下。

**Comment by PeiqinSun** [comment]
已经清理完毕。问题出在以前在机器上尝试安装多个版本的cuda且并未清理, 导致出现空间被占的情况。
