### ISSUE TITLE
Homework2_BUG

### ISSUE THREAD

**Issue by HyperionAhead3** [PeiqinSun/tf-tutorials#50]
环境：win10 + Tensorflow-gpu1.10.0 + GeForce GTX 1050 Ti
运行Homework2_train.py报错如下：
Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
         [[Node: vgg_src/pool1 = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:GPU:0"](vgg_src/conv1_2/Relu)]]

**Comment by chynphh** [comment]
环境应该没有问题，你可以先检查一下是不是磁盘满了..这个实验的保存的文件有点大，可以适当修改一下
（我就是这样的问题）

**Comment by HyperionAhead3** [comment]
环境应该没有问题，你可以先检查一下是不是磁盘满了..这个实验的保存的文件有点大，可以适当修改一下
（我就是这样的问题）

**Comment by zsc** [comment]
问题解决了吗？

**Comment by HyperionAhead3** [comment]
没有

**Comment by perrylover** [comment]
这个报错在某些版本的tensorflow会出现，但并不影响跑实验

**Comment by HyperionAhead3** [comment]
谢谢老师。
我现在在用cpu跑了。

在 2019-03-31 13:02:18，"perrylover" <notifications@github.com> 写道：


这个报错在某些版本的tensorflow会出现，但并不影响跑实验

**Comment by RayXu14** [comment]
同样的问题。但是CPU非常慢

**Comment by zsc** [comment]
> 同样的问题。但是CPU非常慢

CPU 就是很慢，所以不跑extra dataset
