### ISSUE TITLE
作业三的"vgg16-cifar.npy"去哪里下载？

### ISSUE THREAD

**Issue by wxx07** [PeiqinSun/tf-tutorials#54]
还是作业二中的"vgg16_onnx.npy"吗？
可是直接导入，会有报错
KeyError: 'fc1'

另外，custom_vgg16_bn.py 中
`def get_conv_filter(self, name):
        return return tf.constant(self.data_dict[name][0], name="filter") `
应该改成
`def get_conv_filter(self, name):
        return tf.constant(np.rollaxis(np.rollaxis(np.rollaxis(self.data_dict[name][0], 1), 2), 3), name="filter")`
吧

不然会有
ValueError: Dimensions must be equal, but are 3 and 64 for 'conv1_1/BiasAdd' (op: 'BiasAdd') with input shapes: [?,32,32,3], [64].
的报错

**Comment by RayXu14** [comment]
作业说明有啊，详细说明和拉到最后都有

**Comment by chu-tianxiang** [comment]
https://github.com/PeiqinSun/tf-tutorials/blob/master/03-adversarial-examples/model/README.md
