### ISSUE TITLE
what is 'augmented adversarial examples'

### ISSUE THREAD

**Issue by RayXu14** [PeiqinSun/tf-tutorials#58]
**augmented adversarial examples** in hw3 q3

**Comment by wxx07** [comment]
我对这个地方也有疑问：经过增广的对抗样本，用分类器对扩增的部分进行分类，分类结果变好/攻击效果变差 怎么说明“helps defending adversarial attacks”？

我对“helps defending adversarial attacks”的理解是对模型的训练集进行增广之后，对重新训练得到的vgg16-cifar 再次用相同的epoch等生成对抗样本，假如生成的对抗样本相比未增广前，攻击成功率变低了，说明增广能够帮助vgg16-cifar抵抗攻击。

不知道“对抗样本进行增广”这种操作怎么理解，怎么说明有无“helps (model ?) defending adversarial attacks”

**Comment by perrylover** [comment]
对于无目标攻击而言，如果对对抗样本加了增广操作，分类准确度相比于未增加增广操作的对抗样本的分类准确度高，那么可以认为使用增广能帮助抵抗攻击。这里对对抗样本进行增广操作不是对模型的训练集先进行增广再训练生成对抗样本，而是先训练出对抗样本，再对生成的这些样本进行增广操作。
