### ISSUE TITLE
what should we do for hw3 q4?

### ISSUE THREAD

**Issue by RayXu14** [PeiqinSun/tf-tutorials#59]
do not know what to do for q4

**Comment by perrylover** [comment]
q4要求完成目标攻击，因此和前3问不同的是，首先需要为每个图片指定一个target label， 目的是完成攻击生成的对抗样本被分类器识别为这个label; 此外，还需要改loss，使得优化方向: 对抗样本被识别为target label的概率越高，loss越小。

**Comment by RayXu14** [comment]
> q4要求完成目标攻击，因此和前3问不同的是，首先需要为每个图片指定一个target label， 目的是完成攻击生成的对抗样本被分类器识别为这个label; 此外，还需要改loss，使得优化方向: 对抗样本被识别为target label的概率越高，loss越小。

请问这个label是哪来的呀

**Comment by zsc** [comment]
@perrylover 这里目标是随意指定吗？

**Comment by perrylover** [comment]
对，自己指定就好
