### ISSUE TITLE
为啥用tensorboard画出来accuracy的图像跟train.py里print出来的accuracy_avg不相符

### ISSUE THREAD

**Issue by nht2018** [PeiqinSun/tf-tutorials#67]
比如说baseline的图像是这样
![accuracy](https://user-images.githubusercontent.com/42823704/57139201-2a88eb80-6de7-11e9-9177-be40e1872ffa.png)
但是在train.py中输出的accuracy_avg一直是94左右
这是咋回事儿啊

**Comment by zsc** [comment]
@PeiqinSun

**Comment by PeiqinSun** [comment]
1. tensorboard的accuracy是在代码中每次记录的数值. 所以先看看记录的数值是accuracy本身还是accuracy average.
2. tensorboard默认会开启平滑, 请看一下你的平滑系数是否合理
3. 请确认你的tensorboard读取的是对应实验的event.
