### ISSUE TITLE
Nan loss when using lp reg with 0 < p < 1

### ISSUE THREAD

**Issue by kifish** [PeiqinSun/tf-tutorials#68]
作业1中，使用lp reg并设置p=0.5,0.9,0.8都遇到了loss Nan的问题（weight_decay = 1e-3),设置p=-2,1,2,3,4可以正常训练。如果把weight_decay调小至1e-6，似乎可以解决这个问题。当0<p<1，loss会爆炸的原因是什么？

**Comment by zsc** [comment]
p<0时，同时weight decay太大，可能gradient太大。
硬搞是用[gradient clipping](https://machinelearningmastery.com/how-to-avoid-exploding-gradients-in-neural-networks-with-gradient-clipping/) 。但gradient clipping 副作用比较大。
也可以通过调参
