### ISSUE TITLE
请问一下为什么会out memory？

### ISSUE THREAD

**Issue by 857622530** [PeiqinSun/tf-tutorials#69]
![image](https://user-images.githubusercontent.com/31120252/57287934-172d9700-70eb-11e9-84b6-29b2d95302c7.png)

**Comment by kifish** [comment]
这个GPU好像有其他任务占用了内存吧

**Comment by 857622530** [comment]
已解决，中断程序的时候，进程没有马上挂掉，直接把未杀掉的进程手动杀掉就好了
