### ISSUE TITLE
tutorial 代码如何使用？

### ISSUE THREAD

**Issue by yufei1900** [PeiqinSun/tf-tutorials#7]
示例代码感觉很完整，可以直接运行。我们直接运行记录结果就可以？还是需要自己重新写一份不同的代码？

**Comment by PeiqinSun** [comment]
作业的要求是让大家在示例代码的基础上进行修改, 然后得到对应修改后的结果。不需要你们从头开始写。

**Comment by yufei1900** [comment]
好的，谢谢
