### ISSUE TITLE
无法访问tensorboard

### ISSUE THREAD

**Issue by PufanLiu** [PeiqinSun/tf-tutorials#70]
使用分配的gpu，能正常跑程序，但是用不了tensorboard。把链接复制到Chrome里显示无法访问此网站。换了FireFox，IE试过都不行。是哪里有问题呢？

`root@55e9cd9c7a0a:~/01-svhn/baseline# tensorboard --logdir=train_log/`

**Comment by zsc** [comment]
@PeiqinSun  是要ssh 转发吗？

**Comment by PeiqinSun** [comment]
是需要转发的。因为docker的网址并公网IP, 所以不可以直接访问.

**Comment by PeiqinSun** [comment]
可以参考方法: https://blog.csdn.net/weixin_35653315/article/details/71327740
