### ISSUE TITLE
Homework4 Q2 公式错了吧

### ISSUE THREAD

**Issue by yeoyi519** [PeiqinSun/tf-tutorials#71]
Homework4 Q2 中的那个公式
应该是
![image](https://user-images.githubusercontent.com/37505431/57572175-5d675b00-7449-11e9-9962-56d153fc284e.png)
而不是
![image](https://user-images.githubusercontent.com/37505431/57572163-44f74080-7449-11e9-8b8b-3f868f388356.png)
吧?

**Comment by perrylover** [comment]
谢谢，已修
