### ISSUE TITLE
hw6的SR问题中没有prepare_data.py 也没有数据格式的说明

### ISSUE THREAD

**Issue by li-positive-one** [PeiqinSun/tf-tutorials#75]
从链接下载的数据并不直接可用于训练，但是不清楚应该如何预处理数据以匹配baseline程序
可否像其他问题一样提供prepare_data.py  或者给一个训练用的数据的格式说明

**Comment by perrylover** [comment]
训练数据是在dataset.py 中的instance_generator下采样生成，不需要prepare_data.py
